export const CATEGORY_LABELS = {
  ai:        { label: 'AI & Language Models',     color: '#8B5CF6' },
  reviews:   { label: 'Reviews & Community',      color: '#F97316' },
  ecommerce: { label: 'E-commerce & Pricing',     color: '#10B981' },
  database:  { label: 'Databases & Cache',         color: '#3B82F6' },
  email:     { label: 'Email & Notifications',     color: '#F59E0B' },
  webhook:   { label: 'Webhooks & Automation',     color: '#EC4899' },
  custom:    { label: 'Custom',                    color: '#6B7280' },
};

export const KNOWN_CATALOG = [
  { slug: 'gemini',          name: 'Google Gemini',    category: 'ai',        icon_emoji: '🔷', description: 'Gemini Pro / Flash for AI tasks',              config: { model: 'gemini-1.5-pro' } },
  { slug: 'mistral',         name: 'Mistral AI',       category: 'ai',        icon_emoji: '🌬️', description: 'Mistral & Mixtral fast models',               config: { model: 'mistral-large-latest' } },
  { slug: 'cohere',          name: 'Cohere',           category: 'ai',        icon_emoji: '💡', description: 'Command R+ for RAG and enterprise AI',         config: { model: 'command-r-plus' } },
  { slug: 'groq',            name: 'Groq',             category: 'ai',        icon_emoji: '🚀', description: 'Ultra-fast LLM inference',                     config: { model: 'llama3-70b-8192' } },
  { slug: 'perplexity',      name: 'Perplexity',       category: 'ai',        icon_emoji: '🔭', description: 'Search-augmented AI responses',                config: {} },
  { slug: 'walmart',         name: 'Walmart API',      category: 'ecommerce', icon_emoji: '🏪', description: 'Walmart product search and prices',            config: {} },
  { slug: 'cj_affiliate',    name: 'CJ Affiliate',     category: 'ecommerce', icon_emoji: '🤝', description: 'Commission Junction affiliate network',        config: {} },
  { slug: 'rakuten',         name: 'Rakuten Ads',      category: 'ecommerce', icon_emoji: '🟥', description: 'Rakuten affiliate marketing platform',         config: {} },
  { slug: 'mailchimp',       name: 'Mailchimp',        category: 'email',     icon_emoji: '🐵', description: 'Email campaigns and automations',              config: {} },
  { slug: 'postmark',        name: 'Postmark',         category: 'email',     icon_emoji: '📮', description: 'Reliable transactional email',                 config: {} },
  { slug: 'discord_webhook', name: 'Discord Webhook',  category: 'webhook',   icon_emoji: '💜', description: 'Send alerts to Discord channels',              config: {} },
  { slug: 'telegram',        name: 'Telegram Bot',     category: 'webhook',   icon_emoji: '✈️', description: 'Notifications via Telegram bot',               config: {} },
  { slug: 'amazon_reviews',  name: 'Amazon Reviews',   category: 'reviews',   icon_emoji: '📦', description: 'Amazon product reviews data',                  config: {} },
  { slug: 'g2',              name: 'G2 Crowd',         category: 'reviews',   icon_emoji: '📊', description: 'Software and service reviews from G2',         config: {} },
  { slug: 'mongodb',         name: 'MongoDB Atlas',    category: 'database',  icon_emoji: '🍃', description: 'MongoDB Atlas analytics connection',           config: {} },
  { slug: 'clickhouse',      name: 'ClickHouse',       category: 'database',  icon_emoji: '🏠', description: 'Column-store DB for fast analytics',           config: {} },
];

export const CREDENTIAL_FIELDS = {
  claude:        [{ key: 'api_key',        label: 'Anthropic API Key',        type: 'password', placeholder: 'sk-ant-...' }],
  openai:        [{ key: 'api_key',        label: 'OpenAI API Key',           type: 'password', placeholder: 'sk-...' }],
  gemini:        [{ key: 'api_key',        label: 'Google AI API Key',        type: 'password', placeholder: 'AIza...' }],
  mistral:       [{ key: 'api_key',        label: 'Mistral API Key',          type: 'password', placeholder: '' }],
  cohere:        [{ key: 'api_key',        label: 'Cohere API Key',           type: 'password', placeholder: '' }],
  groq:          [{ key: 'api_key',        label: 'Groq API Key',             type: 'password', placeholder: 'gsk_...' }],
  perplexity:    [{ key: 'api_key',        label: 'Perplexity API Key',       type: 'password', placeholder: 'pplx-...' }],
  amazon_pa: [
    { key: 'access_key',  label: 'AWS Access Key ID', type: 'password', placeholder: 'AKIA...' },
    { key: 'secret_key',  label: 'AWS Secret Key',    type: 'password', placeholder: '' },
    { key: 'partner_tag', label: 'Partner Tag',        type: 'text',     placeholder: 'yoursite-20' },
  ],
  ebay:          [{ key: 'api_key',        label: 'eBay App ID',              type: 'password', placeholder: '' }],
  walmart:       [{ key: 'api_key',        label: 'Walmart API Key',          type: 'password', placeholder: '' }],
  cj_affiliate:  [{ key: 'api_key',        label: 'CJ API Key',               type: 'password', placeholder: '' }],
  rakuten:       [{ key: 'api_key',        label: 'Rakuten API Key',          type: 'password', placeholder: '' }],
  sendgrid:      [{ key: 'api_key',        label: 'SendGrid API Key',         type: 'password', placeholder: 'SG...' }],
  resend:        [{ key: 'api_key',        label: 'Resend API Key',           type: 'password', placeholder: 're_...' }],
  mailchimp:     [{ key: 'api_key',        label: 'Mailchimp API Key',        type: 'password', placeholder: '' }],
  postmark:      [{ key: 'api_key',        label: 'Postmark Server Token',    type: 'password', placeholder: '' }],
  slack_webhook: [{ key: 'webhook_url',    label: 'Slack Webhook URL',        type: 'text',     placeholder: 'https://hooks.slack.com/...' }],
  zapier:        [{ key: 'webhook_url',    label: 'Zapier Webhook URL',       type: 'text',     placeholder: 'https://hooks.zapier.com/...' }],
  discord_webhook: [{ key: 'webhook_url', label: 'Discord Webhook URL',      type: 'text',     placeholder: 'https://discord.com/api/webhooks/...' }],
  telegram: [
    { key: 'bot_token', label: 'Bot Token', type: 'password', placeholder: '123456:ABC-...' },
    { key: 'chat_id',   label: 'Chat ID',    type: 'text',     placeholder: '-100...' },
  ],
  redis:         [{ key: 'connection_url', label: 'Redis URL',                type: 'password', placeholder: 'rediss://...' }],
  postgres_read: [{ key: 'connection_url', label: 'Connection String',        type: 'password', placeholder: 'postgresql://...' }],
  mongodb:       [{ key: 'connection_url', label: 'MongoDB URI',              type: 'password', placeholder: 'mongodb+srv://...' }],
  clickhouse:    [{ key: 'connection_url', label: 'ClickHouse URL',           type: 'password', placeholder: 'https://host:8443' }],
  google_sheets: [
    { key: 'service_account_email', label: 'Service Account Email', type: 'text',     placeholder: '...@....iam.gserviceaccount.com' },
    { key: 'private_key',           label: 'Private Key (JSON)',    type: 'password', placeholder: '' },
  ],
  google_search: [
    { key: 'api_key', label: 'Google API Key',          type: 'password', placeholder: 'AIza...' },
    { key: 'cx',      label: 'Custom Search Engine ID', type: 'text',     placeholder: '017...' },
  ],
  reddit: [
    { key: 'client_id',     label: 'Client ID',     type: 'password', placeholder: 'From reddit.com/prefs/apps' },
    { key: 'client_secret', label: 'Client Secret', type: 'password', placeholder: '' },
    { key: 'user_agent',    label: 'User Agent',    type: 'text',     placeholder: 'MajorLogic/1.0' },
  ],
  youtube:        [{ key: 'api_key', label: 'YouTube Data API v3 Key', type: 'password', placeholder: 'AIza...' }],
  bestbuy:        [{ key: 'api_key', label: 'Best Buy API Key',        type: 'password', placeholder: '' }],
  trustpilot: [
    { key: 'api_key',    label: 'Trustpilot API Key',    type: 'password', placeholder: '' },
    { key: 'api_secret', label: 'Trustpilot API Secret', type: 'password', placeholder: '' },
  ],
  serpapi:        [{ key: 'api_key', label: 'SerpAPI Key',  type: 'password', placeholder: '' }],
  amazon_reviews: [{ key: 'api_key', label: 'API Key',      type: 'password', placeholder: '' }],
  g2:             [{ key: 'api_key', label: 'G2 API Key',   type: 'password', placeholder: '' }],
  custom_api: [
    { key: 'base_url', label: 'Base URL', type: 'text',     placeholder: 'https://api.example.com' },
    { key: 'api_key',  label: 'API Key',  type: 'password', placeholder: '' },
  ],
};
